language: generic 

os: linux
dist: focal
services:
  - docker

before_install:
  - docker build -t sarkis1231/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sarkis1231/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket: "elasticbeanstalk-us-east-2-802665291802"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 
  on:
    branch: master
