language: generic 

os: linux
dist: focal
services:
  - docker

before_install:
  - docker build -t sarkis1231/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sarkis1231/docker-react yarn test
  - rm docker-compose.yml
  # to be sure that the docker-compose.yml was deleted successfully
  - ls
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "test-1"
  env: "Test1-env"
  bucket: "elasticbeanstalk-us-east-2-802665291802"
  bucket_path: "test-1"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 
  on:
    branch: master
