language: generic 
os: linux
sudo: required
services:
  - docker

before_Install:
  - docker build -t sarkis1231/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sarkis1231/docker-react yarn test